[package]
name = "interperter"
version = "0.1.0"
edition = "2021"


[dependencies]
env_logger = "0.11.6"
log = "0.4.25"
logos = "0.14.2"
regex = "1.11.1"
rustyline = "8.0.0"

[profile.dev]
debug = false

[profile.release]
debug = false
